{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-core",
    "version": "7.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-crypto",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "7.0.8"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-core-7.0.6.jar",
          "url": "spring-security-core-7.0.6.jar",
          "size": 618064,
          "sha512": "1746d6997140dbb5cfae668f4b12d6ac10d6f4885113ae4998b3f632b65da07a992d93134230785202dd7ab3d06fe8c11081b5d32e394df7b8312ed751536c53",
          "sha256": "f9e1aebb39e051f6f92be029a6fca31e2977a06d417aa51504bfb298bc2a7c69",
          "sha1": "74a38616f47ee75fc3ea25ad5d44509082d4529f",
          "md5": "54654a0fb613c68d156d6fcdb9165b7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-crypto",
          "version": {
            "requires": "7.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "7.0.8"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-core-7.0.6.jar",
          "url": "spring-security-core-7.0.6.jar",
          "size": 618064,
          "sha512": "1746d6997140dbb5cfae668f4b12d6ac10d6f4885113ae4998b3f632b65da07a992d93134230785202dd7ab3d06fe8c11081b5d32e394df7b8312ed751536c53",
          "sha256": "f9e1aebb39e051f6f92be029a6fca31e2977a06d417aa51504bfb298bc2a7c69",
          "sha1": "74a38616f47ee75fc3ea25ad5d44509082d4529f",
          "md5": "54654a0fb613c68d156d6fcdb9165b7e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-core-7.0.6-javadoc.jar",
          "url": "spring-security-core-7.0.6-javadoc.jar",
          "size": 1326437,
          "sha512": "57b8650d5116a6340470ec41447b52efee52d1d126e417c05b801c5b67e3c8e67b7ec32f68a528eb24ba2817de401f4f8256d55c95e1efefc2af550a4c4f44e9",
          "sha256": "f8fa9d1ab05c76cc62154cd19486e1cf0f148ba80f7ab1d6d0bad8a87fd31b24",
          "sha1": "679aa89488963d474b78a5fdb12845d5deb33859",
          "md5": "f9e0488b31c56b2c66b3099b956db1bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-core-7.0.6-sources.jar",
          "url": "spring-security-core-7.0.6-sources.jar",
          "size": 551246,
          "sha512": "f157c8a0a6482e827a6a717bcacbfaa6337360cf7195e6889b314f3c10a74c5e7aae24bb8511e63671414247368f946e6a1b5b6b7327d61f4e1d8b3fa112f134",
          "sha256": "73d208a0dd021cad8cbbb85a71c8efc66df0161f49e91cd9d877a55def6bc9d0",
          "sha1": "4e0e61a1e992a667518af6d5c947ce0c0a64359a",
          "md5": "d33b040af132fd6bd9a0d49863c7e99d"
        },
        {
          "name": "spring-security-core-7.0.6-sources.jar",
          "url": "spring-security-core-7.0.6-sources.jar",
          "size": 551246,
          "sha512": "f157c8a0a6482e827a6a717bcacbfaa6337360cf7195e6889b314f3c10a74c5e7aae24bb8511e63671414247368f946e6a1b5b6b7327d61f4e1d8b3fa112f134",
          "sha256": "73d208a0dd021cad8cbbb85a71c8efc66df0161f49e91cd9d877a55def6bc9d0",
          "sha1": "4e0e61a1e992a667518af6d5c947ce0c0a64359a",
          "md5": "d33b040af132fd6bd9a0d49863c7e99d"
        }
      ]
    }
  ]
}
