{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-webmvc",
    "version": "4.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-http-converter",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webmvc",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webmvc-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-starter-webmvc-4.0.8-SNAPSHOT.jar",
          "size": 4767,
          "sha512": "b27935bce90e37c314cf4a8d60ff976c1fa1a4fdb182ad52b0adedb9527030231a15e2a0fdb9e5a960127d8fbef1f861910e1533eb17ce2018a8c0d398275b91",
          "sha256": "622901c2ea531da32b1eb94ac925917dfe6091c7e12a0804a7e305818cc88ca2",
          "sha1": "30ae2ca3b9bab221a4ad191c008e6b6bc80465a5",
          "md5": "019b2c091ff99398b5cfec2910bd03ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-http-converter",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webmvc",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webmvc-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-starter-webmvc-4.0.8-SNAPSHOT.jar",
          "size": 4767,
          "sha512": "b27935bce90e37c314cf4a8d60ff976c1fa1a4fdb182ad52b0adedb9527030231a15e2a0fdb9e5a960127d8fbef1f861910e1533eb17ce2018a8c0d398275b91",
          "sha256": "622901c2ea531da32b1eb94ac925917dfe6091c7e12a0804a7e305818cc88ca2",
          "sha1": "30ae2ca3b9bab221a4ad191c008e6b6bc80465a5",
          "md5": "019b2c091ff99398b5cfec2910bd03ac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webmvc-4.0.8-SNAPSHOT-javadoc.jar",
          "url": "spring-boot-starter-webmvc-4.0.8-SNAPSHOT-javadoc.jar",
          "size": 4767,
          "sha512": "b27935bce90e37c314cf4a8d60ff976c1fa1a4fdb182ad52b0adedb9527030231a15e2a0fdb9e5a960127d8fbef1f861910e1533eb17ce2018a8c0d398275b91",
          "sha256": "622901c2ea531da32b1eb94ac925917dfe6091c7e12a0804a7e305818cc88ca2",
          "sha1": "30ae2ca3b9bab221a4ad191c008e6b6bc80465a5",
          "md5": "019b2c091ff99398b5cfec2910bd03ac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webmvc-4.0.8-SNAPSHOT-sources.jar",
          "url": "spring-boot-starter-webmvc-4.0.8-SNAPSHOT-sources.jar",
          "size": 4767,
          "sha512": "b27935bce90e37c314cf4a8d60ff976c1fa1a4fdb182ad52b0adedb9527030231a15e2a0fdb9e5a960127d8fbef1f861910e1533eb17ce2018a8c0d398275b91",
          "sha256": "622901c2ea531da32b1eb94ac925917dfe6091c7e12a0804a7e305818cc88ca2",
          "sha1": "30ae2ca3b9bab221a4ad191c008e6b6bc80465a5",
          "md5": "019b2c091ff99398b5cfec2910bd03ac"
        }
      ]
    }
  ]
}
