{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-logging",
    "version": "4.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.34"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.25.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.18"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-starter-logging-4.0.8-SNAPSHOT.jar",
          "size": 4761,
          "sha512": "d31dba4dbca2c173e04daead65a22dab19854c2d789405489eaee9873f301e4c5d27821254f78965f5522f35b6ab73a0eeb29475997bfd9ad0b88529dfd57946",
          "sha256": "44bc23bf6d949e2f4361a1dbb4c29a560c9d1d8b0549167ba99e13e3a53c80bd",
          "sha1": "c98cdca62804af425685030df96544a4196c7b00",
          "md5": "197ab8f5e11c65284b26789545295bcf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.34"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.25.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.18"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-starter-logging-4.0.8-SNAPSHOT.jar",
          "size": 4761,
          "sha512": "d31dba4dbca2c173e04daead65a22dab19854c2d789405489eaee9873f301e4c5d27821254f78965f5522f35b6ab73a0eeb29475997bfd9ad0b88529dfd57946",
          "sha256": "44bc23bf6d949e2f4361a1dbb4c29a560c9d1d8b0549167ba99e13e3a53c80bd",
          "sha1": "c98cdca62804af425685030df96544a4196c7b00",
          "md5": "197ab8f5e11c65284b26789545295bcf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-4.0.8-SNAPSHOT-javadoc.jar",
          "url": "spring-boot-starter-logging-4.0.8-SNAPSHOT-javadoc.jar",
          "size": 4761,
          "sha512": "d31dba4dbca2c173e04daead65a22dab19854c2d789405489eaee9873f301e4c5d27821254f78965f5522f35b6ab73a0eeb29475997bfd9ad0b88529dfd57946",
          "sha256": "44bc23bf6d949e2f4361a1dbb4c29a560c9d1d8b0549167ba99e13e3a53c80bd",
          "sha1": "c98cdca62804af425685030df96544a4196c7b00",
          "md5": "197ab8f5e11c65284b26789545295bcf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-4.0.8-SNAPSHOT-sources.jar",
          "url": "spring-boot-starter-logging-4.0.8-SNAPSHOT-sources.jar",
          "size": 4761,
          "sha512": "d31dba4dbca2c173e04daead65a22dab19854c2d789405489eaee9873f301e4c5d27821254f78965f5522f35b6ab73a0eeb29475997bfd9ad0b88529dfd57946",
          "sha256": "44bc23bf6d949e2f4361a1dbb4c29a560c9d1d8b0549167ba99e13e3a53c80bd",
          "sha1": "c98cdca62804af425685030df96544a4196c7b00",
          "md5": "197ab8f5e11c65284b26789545295bcf"
        }
      ]
    }
  ]
}
