{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-jdbc",
    "version": "4.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-sql",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-transaction",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "7.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-jdbc-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-jdbc-4.0.8-SNAPSHOT.jar",
          "size": 201315,
          "sha512": "41ec6f9f79e9eea99e0f07427d0a00f97bbf70bf5a3d1cc5d5e61f51d6fb505caf88d48e5838065b9dfd8441d458fda854abd1c9b59584546dc191525bd7a679",
          "sha256": "86ad8c0dd4cdf42d231819f0d76212a446d63d024a85c39d1b3f79baefd5980a",
          "sha1": "eb93da68366e5707e9f792febf456449e5b6d5c3",
          "md5": "b5e9d7b416bacac9efd473133d5954d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-sql",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-transaction",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "7.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-jdbc-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-jdbc-4.0.8-SNAPSHOT.jar",
          "size": 201315,
          "sha512": "41ec6f9f79e9eea99e0f07427d0a00f97bbf70bf5a3d1cc5d5e61f51d6fb505caf88d48e5838065b9dfd8441d458fda854abd1c9b59584546dc191525bd7a679",
          "sha256": "86ad8c0dd4cdf42d231819f0d76212a446d63d024a85c39d1b3f79baefd5980a",
          "sha1": "eb93da68366e5707e9f792febf456449e5b6d5c3",
          "md5": "b5e9d7b416bacac9efd473133d5954d5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-jdbc-4.0.8-SNAPSHOT-javadoc.jar",
          "url": "spring-boot-jdbc-4.0.8-SNAPSHOT-javadoc.jar",
          "size": 288320,
          "sha512": "c92f106a772b2553ad00b4c096dda9b1ae87682f7c580ede22996bd80d1d0756eb695699c7320ccd6e52783e4444bd735620d7cb597b428c24a81da9e1082ac8",
          "sha256": "483e59e23047e95cfa7b5e1beae8365f68a64700795dc93dad7cb64d3632f375",
          "sha1": "8e28beff8fc8772be537e30c25c885ccf8eac87c",
          "md5": "69e5112788203debc026ce932f44abd3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-jdbc-4.0.8-SNAPSHOT-sources.jar",
          "url": "spring-boot-jdbc-4.0.8-SNAPSHOT-sources.jar",
          "size": 115506,
          "sha512": "3a8d96af357e700c0e597181817be1c26725d697eba7da451adf44876791c730bdce814feda7fa58055b50adaca81df1505de336438176a0d81260c7264234bd",
          "sha256": "840ffe9b9803187ab8fb2dffd59f9103112108450f83b2fbc90ef46912eca12f",
          "sha1": "7bfbdde8101645b78fd88cba1ff2caa273ccd91b",
          "md5": "3c8b8336d39558684c7532840c0b165c"
        }
      ]
    }
  ]
}
