{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "4.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-starter-4.0.8-SNAPSHOT.jar",
          "size": 4787,
          "sha512": "31dd673f02bf8544195c163a76972627b4dc07604d4125d72218fa961c05d81d4f193c040b39c327c4868752459f793d628778d7cf4c4d9ac6a50a1628dd2a42",
          "sha256": "1b3f2b137f10a7e3a63258a604b1fadd200af0cf2181805462b8e89f57a8e88b",
          "sha1": "7b0136f8a37efc0f11bb804d12c50f74f1c3a1ef",
          "md5": "63ce5479dd10d3b9c70b4ab45d2f51a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-starter-4.0.8-SNAPSHOT.jar",
          "size": 4787,
          "sha512": "31dd673f02bf8544195c163a76972627b4dc07604d4125d72218fa961c05d81d4f193c040b39c327c4868752459f793d628778d7cf4c4d9ac6a50a1628dd2a42",
          "sha256": "1b3f2b137f10a7e3a63258a604b1fadd200af0cf2181805462b8e89f57a8e88b",
          "sha1": "7b0136f8a37efc0f11bb804d12c50f74f1c3a1ef",
          "md5": "63ce5479dd10d3b9c70b4ab45d2f51a5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-4.0.8-SNAPSHOT-javadoc.jar",
          "url": "spring-boot-starter-4.0.8-SNAPSHOT-javadoc.jar",
          "size": 4787,
          "sha512": "31dd673f02bf8544195c163a76972627b4dc07604d4125d72218fa961c05d81d4f193c040b39c327c4868752459f793d628778d7cf4c4d9ac6a50a1628dd2a42",
          "sha256": "1b3f2b137f10a7e3a63258a604b1fadd200af0cf2181805462b8e89f57a8e88b",
          "sha1": "7b0136f8a37efc0f11bb804d12c50f74f1c3a1ef",
          "md5": "63ce5479dd10d3b9c70b4ab45d2f51a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-4.0.8-SNAPSHOT-sources.jar",
          "url": "spring-boot-starter-4.0.8-SNAPSHOT-sources.jar",
          "size": 4787,
          "sha512": "31dd673f02bf8544195c163a76972627b4dc07604d4125d72218fa961c05d81d4f193c040b39c327c4868752459f793d628778d7cf4c4d9ac6a50a1628dd2a42",
          "sha256": "1b3f2b137f10a7e3a63258a604b1fadd200af0cf2181805462b8e89f57a8e88b",
          "sha1": "7b0136f8a37efc0f11bb804d12c50f74f1c3a1ef",
          "md5": "63ce5479dd10d3b9c70b4ab45d2f51a5"
        }
      ]
    }
  ]
}
