{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-persistence",
    "version": "4.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "7.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-persistence-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-persistence-4.0.8-SNAPSHOT.jar",
          "size": 16050,
          "sha512": "d70971422ba92efc47e3ce2e72c3456756c13472cdcbed1b6c64745e4dd2c601459fd755bfcabd90713f05df2b2ab3c3da0e1a45b9496a30dbade4aa7a87fcb6",
          "sha256": "42a3ff926b50c9b9a363fa13b5936313decafba41d9c69d40f381f17a7cb156e",
          "sha1": "3f4bc17d5cdc5855ae5f202627d351ec4aace700",
          "md5": "07c32d620e43de69ca9603ca47a721d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "7.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-persistence-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-persistence-4.0.8-SNAPSHOT.jar",
          "size": 16050,
          "sha512": "d70971422ba92efc47e3ce2e72c3456756c13472cdcbed1b6c64745e4dd2c601459fd755bfcabd90713f05df2b2ab3c3da0e1a45b9496a30dbade4aa7a87fcb6",
          "sha256": "42a3ff926b50c9b9a363fa13b5936313decafba41d9c69d40f381f17a7cb156e",
          "sha1": "3f4bc17d5cdc5855ae5f202627d351ec4aace700",
          "md5": "07c32d620e43de69ca9603ca47a721d5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-persistence-4.0.8-SNAPSHOT-javadoc.jar",
          "url": "spring-boot-persistence-4.0.8-SNAPSHOT-javadoc.jar",
          "size": 117909,
          "sha512": "9f494215a612d811397d33f4b11eb9c5c94f590e48a31fc42382aca0881130a67dc5781cb11847d76ceb3bf63a91533b614ed82f0710de2064d537908dbc98b6",
          "sha256": "15ec6bf6db8e6d3302a4fce70e114d80f1858a49deb8f358dd4af5470a2bb327",
          "sha1": "770c660cf79608cb71b43b1ad66c1515b57ae4e3",
          "md5": "1c67e36d5ec665ebb0a102fbecfd2e68"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-persistence-4.0.8-SNAPSHOT-sources.jar",
          "url": "spring-boot-persistence-4.0.8-SNAPSHOT-sources.jar",
          "size": 13248,
          "sha512": "db1d5ce77eaa5490bac23c6ad143ada7d42415fbca6b70f6248c1b2bdb1f0a67e5fe191d795ce5ef549f5fd8c0c2f82885422a21d3ec53aa67bf592fa1b78502",
          "sha256": "f9a277a3b5007dc97e6382255c8e454aeabe95afcde76db86ea2ae520a5bcefd",
          "sha1": "bb3397cf06ba55a5923eb65ad8c88b3c4c686c35",
          "md5": "f4f0fb9a9bfe3b17c8c37c55cac1ecb3"
        }
      ]
    }
  ]
}
