{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-gradle-plugin",
    "version": "4.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-gradle-plugin-4.0.8-SNAPSHOT.jar",
          "size": 148662,
          "sha512": "5a9a1ac3022ee58da6d4fb8efd00e04e316fd7c42588be1d6848b5ef37a9d578b65c978b88494e328abaeb6cf532e9b1b2b6b3d3ff33622828ea4d9245a8babd",
          "sha256": "3489ca502159153fe913ff12d4049d73653cedf6250360a95303dcb591d6ccc3",
          "sha1": "9ea3ccde9c0b26c0ebba187a46d153eb93a44642",
          "md5": "fc41fd65be2c59134072e2e31b491bb6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-buildpack-platform",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-loader-tools",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "io.spring.gradle",
          "module": "dependency-management-plugin",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-gradle-plugin-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-gradle-plugin-4.0.8-SNAPSHOT.jar",
          "size": 148662,
          "sha512": "5a9a1ac3022ee58da6d4fb8efd00e04e316fd7c42588be1d6848b5ef37a9d578b65c978b88494e328abaeb6cf532e9b1b2b6b3d3ff33622828ea4d9245a8babd",
          "sha256": "3489ca502159153fe913ff12d4049d73653cedf6250360a95303dcb591d6ccc3",
          "sha1": "9ea3ccde9c0b26c0ebba187a46d153eb93a44642",
          "md5": "fc41fd65be2c59134072e2e31b491bb6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-4.0.8-SNAPSHOT-javadoc.jar",
          "url": "spring-boot-gradle-plugin-4.0.8-SNAPSHOT-javadoc.jar",
          "size": 348796,
          "sha512": "cebba9d28a505d65616eeca4233f117d69c87555a838add70f114c2a7b8527d470834da304a084c1d17bf6df6e474d1c0f9329bc7f137ba0f03dc4c27632c80e",
          "sha256": "2b8ede1e63abd8a77543923295e90b9cf3a19692885a988c523c86f12677853f",
          "sha1": "6a41352b72180189df29a9f5293eb390fbba800a",
          "md5": "92433431b2e9e3f47d5ecdb8351187e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-4.0.8-SNAPSHOT-sources.jar",
          "url": "spring-boot-gradle-plugin-4.0.8-SNAPSHOT-sources.jar",
          "size": 82407,
          "sha512": "322823fee39eba10352667f1fdd55478d2784556c34bee754ca7ae6724d0dc08d375c2017706980e6f7c4c5db01f68b0f49a29e2f9bb62983226f119837a9b2a",
          "sha256": "90f56cb7dcb6335d6b1f0a402de60b0cb5f31cf1b27ac36fc25f7c1d8f52e1b8",
          "sha1": "3d6aa18be05ad7282a3ec2716dabf7965e8c5699",
          "md5": "6ae3a2d5ef0b89dc2921ed69f8ebc84a"
        }
      ]
    }
  ]
}
