{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-web-server",
    "version": "4.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-web-server-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-web-server-4.0.8-SNAPSHOT.jar",
          "size": 169258,
          "sha512": "2a2c82fb9fcf38ba7ee5af81c9e5930cf515fd3750136affb20a7a567f4598d31e24ecb733fcab461ecfef014522187db221279f4e1bf3b3ea26679c8c7c6b7e",
          "sha256": "9945c7136ab6e39fce81ab1d41d1153b69b243b2a2fbaf961be201746bde9841",
          "sha1": "baf27a89ac9624cfb78e56b02e717e17c33c1a12",
          "md5": "3cc49060ff719216a6a88d02bd0189e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-web-server-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-web-server-4.0.8-SNAPSHOT.jar",
          "size": 169258,
          "sha512": "2a2c82fb9fcf38ba7ee5af81c9e5930cf515fd3750136affb20a7a567f4598d31e24ecb733fcab461ecfef014522187db221279f4e1bf3b3ea26679c8c7c6b7e",
          "sha256": "9945c7136ab6e39fce81ab1d41d1153b69b243b2a2fbaf961be201746bde9841",
          "sha1": "baf27a89ac9624cfb78e56b02e717e17c33c1a12",
          "md5": "3cc49060ff719216a6a88d02bd0189e5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-web-server-4.0.8-SNAPSHOT-javadoc.jar",
          "url": "spring-boot-web-server-4.0.8-SNAPSHOT-javadoc.jar",
          "size": 411908,
          "sha512": "54c95b13b42b439af458ca103e554990af6653a0a10c9af3a7118f55f911f91a4ac5b97f5a768ee2235b8199aaaaae1ef4ffe277402a614aa47758ab0ad0d86a",
          "sha256": "1a0865ae7e02587bab4d47397905fc3a3d694eab0cfa050b6fa7b714be8418f6",
          "sha1": "d6526ee7ee63421a0f874ab9ade9ab8837f159dc",
          "md5": "2f56c48056ccc2f1f15a8455e7039498"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-web-server-4.0.8-SNAPSHOT-sources.jar",
          "url": "spring-boot-web-server-4.0.8-SNAPSHOT-sources.jar",
          "size": 129329,
          "sha512": "1452819e71b5bf6ac13fc0526d3e3b96824d3fecfcc3fdf635d08fb33f9dd6044b0778941ba4e5fb4e0158d432e8c4789c9d525cdf270d1fa13339572fa963f7",
          "sha256": "0ffbf7ed67cee1d54e64049c03b6f5598ab5c6d5a000abdb68249fed208ad31b",
          "sha1": "d3f02cc408f68b066c50021ceb791705e2805da8",
          "md5": "22c518cf310cb402e7335f9fdd58a0ca"
        }
      ]
    }
  ]
}
