{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-thymeleaf",
    "version": "4.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.thymeleaf",
          "module": "thymeleaf-spring6",
          "version": {
            "requires": "3.1.5.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-thymeleaf-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-thymeleaf-4.0.8-SNAPSHOT.jar",
          "size": 30619,
          "sha512": "590f87c0f6869c00648971be76cef17ad8cb2f5230c501b1c604ceda43fe699936b0153b7c9891d5800dffc187989ae33f3d160f122feb956bc94cc13e92955e",
          "sha256": "84b77c5373799bcafcbf43d9f36bb3c77c69127d96d0336f3b33e8e093db3ff0",
          "sha1": "f15365daa2b637bd095742684f3fc0da62ee774d",
          "md5": "90e11973b86c7a56fbb6b30277aac5b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.thymeleaf",
          "module": "thymeleaf-spring6",
          "version": {
            "requires": "3.1.5.RELEASE"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-thymeleaf-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-thymeleaf-4.0.8-SNAPSHOT.jar",
          "size": 30619,
          "sha512": "590f87c0f6869c00648971be76cef17ad8cb2f5230c501b1c604ceda43fe699936b0153b7c9891d5800dffc187989ae33f3d160f122feb956bc94cc13e92955e",
          "sha256": "84b77c5373799bcafcbf43d9f36bb3c77c69127d96d0336f3b33e8e093db3ff0",
          "sha1": "f15365daa2b637bd095742684f3fc0da62ee774d",
          "md5": "90e11973b86c7a56fbb6b30277aac5b1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-thymeleaf-4.0.8-SNAPSHOT-javadoc.jar",
          "url": "spring-boot-thymeleaf-4.0.8-SNAPSHOT-javadoc.jar",
          "size": 124258,
          "sha512": "b8116d5fbecb3c265395f2a8cfbb834a70d0797176df8a774e4adb156751f953a8c57b7c01fab96a21a4a1e10c6ab17e6f1d1cf77a47b1e8b5cac285ff1b4a77",
          "sha256": "263df06439d64be756684091047fe309078035930f4e264a5e7a19a85651cea3",
          "sha1": "097db283b441bbb24686b793c0f031a4c68a0edc",
          "md5": "b8c6b9795b06386952fe035215eae398"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-thymeleaf-4.0.8-SNAPSHOT-sources.jar",
          "url": "spring-boot-thymeleaf-4.0.8-SNAPSHOT-sources.jar",
          "size": 16154,
          "sha512": "bb461d97251198cfee65e0db4b4297ec02607607632d257d3df72ce1717a459d4287d667bc7fe52028b1efd5cf82726ce966c3aee2de85df598d92fcb3523ef0",
          "sha256": "d6c6033a2c67fd15656550ff93b94f76ddb7587cad5d13260d98861c59b2f5cd",
          "sha1": "76729aaf3139d098da2b41ac770c4e614fc26e8a",
          "md5": "98f4b606dc7a404b8d10e6ccfd445903"
        }
      ]
    }
  ]
}
