{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-websocket",
    "version": "4.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "7.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-websocket",
          "version": {
            "requires": "7.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-websocket-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-websocket-4.0.8-SNAPSHOT.jar",
          "size": 16319,
          "sha512": "922c678d18788d72926635ff832c3cd0f0e2b2dfc626e498401f1a5554b6c93c7f45d510a1e92a992cff9bdf73c1b3df7b9ee7eff266c874666877c20db21b7c",
          "sha256": "0ef34bfff82a3e77c60698fa5db4b761777629c627c85813c81d9b6536678a1d",
          "sha1": "17e54e6e2edb228677745cf035bc009beae824ad",
          "md5": "e7279ab40e337bb57eb4822bc602282f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "7.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-websocket",
          "version": {
            "requires": "7.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-websocket-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-websocket-4.0.8-SNAPSHOT.jar",
          "size": 16319,
          "sha512": "922c678d18788d72926635ff832c3cd0f0e2b2dfc626e498401f1a5554b6c93c7f45d510a1e92a992cff9bdf73c1b3df7b9ee7eff266c874666877c20db21b7c",
          "sha256": "0ef34bfff82a3e77c60698fa5db4b761777629c627c85813c81d9b6536678a1d",
          "sha1": "17e54e6e2edb228677745cf035bc009beae824ad",
          "md5": "e7279ab40e337bb57eb4822bc602282f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-websocket-4.0.8-SNAPSHOT-javadoc.jar",
          "url": "spring-boot-websocket-4.0.8-SNAPSHOT-javadoc.jar",
          "size": 106801,
          "sha512": "808f10a2b9e286785de472d5ab27121759491812c7132e5c62a8a7b022f372e329ddc9c2b59339f7b5fb6bad0711569881051754c89f9a43ea9791fdf78fcbd4",
          "sha256": "f58b26b1893d635821c97c3b125d1167e2e849a721c5222a910fc00cc35cf4fb",
          "sha1": "6ad7b335b99da04cad8777c9a3ed22669217f9a2",
          "md5": "aa14fa11b5c21ab0ddee71ee19f9146a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-websocket-4.0.8-SNAPSHOT-sources.jar",
          "url": "spring-boot-websocket-4.0.8-SNAPSHOT-sources.jar",
          "size": 9336,
          "sha512": "9f9ee9955334b2ac4578cbf63612ded66daec86bd2c81db7909d25ea894c9fea0267ea0487aa1c79247205fa8c4ac6c3777eacdd14eef06d47ac2164dbb019fb",
          "sha256": "a2230b020845f728aefc18eb0c2ed106a12ec0c4412396d7cb724bf461623943",
          "sha1": "b3463f3eac4be2c48c81c2edc3209dd79211e836",
          "md5": "81edd3a6e4bc66dd74be755dfb1fb0e9"
        }
      ]
    }
  ]
}
