{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat-runtime",
    "version": "4.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "11.0.22"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "11.0.22"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "11.0.22"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.8-SNAPSHOT.jar",
          "size": 4764,
          "sha512": "cdffb510773f626fe31846fcc06959855b893622d035df5ad9eadc34056507c1e8173ff1e1c47d05d43cfc8971ad48d9cf871f3468d4b9befaf406a0188be2bc",
          "sha256": "a798f0e6f19752a821df7b0a883c4aed7843b6d836b628ac73547d63d97b11fb",
          "sha1": "85da5b0b9bcd81d92fd07dad2cdbfb8ea582485b",
          "md5": "0734903e31c51e407f65b345f94322ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "11.0.22"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "11.0.22"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "11.0.22"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.8-SNAPSHOT.jar",
          "size": 4764,
          "sha512": "cdffb510773f626fe31846fcc06959855b893622d035df5ad9eadc34056507c1e8173ff1e1c47d05d43cfc8971ad48d9cf871f3468d4b9befaf406a0188be2bc",
          "sha256": "a798f0e6f19752a821df7b0a883c4aed7843b6d836b628ac73547d63d97b11fb",
          "sha1": "85da5b0b9bcd81d92fd07dad2cdbfb8ea582485b",
          "md5": "0734903e31c51e407f65b345f94322ed"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.8-SNAPSHOT-javadoc.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.8-SNAPSHOT-javadoc.jar",
          "size": 4764,
          "sha512": "cdffb510773f626fe31846fcc06959855b893622d035df5ad9eadc34056507c1e8173ff1e1c47d05d43cfc8971ad48d9cf871f3468d4b9befaf406a0188be2bc",
          "sha256": "a798f0e6f19752a821df7b0a883c4aed7843b6d836b628ac73547d63d97b11fb",
          "sha1": "85da5b0b9bcd81d92fd07dad2cdbfb8ea582485b",
          "md5": "0734903e31c51e407f65b345f94322ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.8-SNAPSHOT-sources.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.8-SNAPSHOT-sources.jar",
          "size": 4764,
          "sha512": "cdffb510773f626fe31846fcc06959855b893622d035df5ad9eadc34056507c1e8173ff1e1c47d05d43cfc8971ad48d9cf871f3468d4b9befaf406a0188be2bc",
          "sha256": "a798f0e6f19752a821df7b0a883c4aed7843b6d836b628ac73547d63d97b11fb",
          "sha1": "85da5b0b9bcd81d92fd07dad2cdbfb8ea582485b",
          "md5": "0734903e31c51e407f65b345f94322ed"
        }
      ]
    }
  ]
}
