{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-sql",
    "version": "4.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-sql-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-sql-4.0.8-SNAPSHOT.jar",
          "size": 36078,
          "sha512": "cd4693653c965572fcf746645e72933d6916477b731dfb58590b776c999969f7ff1fce1fa8a9b49f99f67138b20ee4a1f410481146bfac2f0a0f5f1e4c99f3da",
          "sha256": "acfa3f4026b1b8a5e3714204dd5bb04cf89e3d64cae725976fc3e86df189925d",
          "sha1": "03dbff16bdc9dfc221be92bb5ee319cfccd2939a",
          "md5": "f72f7477e3748f1cab955f8810170020"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-sql-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-sql-4.0.8-SNAPSHOT.jar",
          "size": 36078,
          "sha512": "cd4693653c965572fcf746645e72933d6916477b731dfb58590b776c999969f7ff1fce1fa8a9b49f99f67138b20ee4a1f410481146bfac2f0a0f5f1e4c99f3da",
          "sha256": "acfa3f4026b1b8a5e3714204dd5bb04cf89e3d64cae725976fc3e86df189925d",
          "sha1": "03dbff16bdc9dfc221be92bb5ee319cfccd2939a",
          "md5": "f72f7477e3748f1cab955f8810170020"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-sql-4.0.8-SNAPSHOT-javadoc.jar",
          "url": "spring-boot-sql-4.0.8-SNAPSHOT-javadoc.jar",
          "size": 163691,
          "sha512": "8af506de3999e1f98c9b09d1ff5f960e83e067502cf068dcba87fc308f2fe0adad8a7863c0e82deabcce2ac925f7f85b3091f17f7f1714dcae6fb144ea1c1c83",
          "sha256": "e71c321c5876e742874f74f1af0a96094295097c57268df1ac20ccc5b80a89c1",
          "sha1": "0dd58b7543f4287a75d1ac824acbc7b40f1ef42e",
          "md5": "f2572fbdd7ab57a6c31550022641273c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-sql-4.0.8-SNAPSHOT-sources.jar",
          "url": "spring-boot-sql-4.0.8-SNAPSHOT-sources.jar",
          "size": 30657,
          "sha512": "7ab1628fc66fbfa00cb709b5a2a049758e69d17928dd8b968454733a1a9cb7a98d9c6b83c5e850a545c3d368e94b530441f89822dde86570482e8d2b586bcdb5",
          "sha256": "844eff6332b11a98486ccfe757a73eba4d0679bba7520535441e41863a9bbaa9",
          "sha1": "4de898a2204eadc0297981e250b2a56267495783",
          "md5": "2ac2100d81666cabd41d96fc952cdf17"
        }
      ]
    }
  ]
}
