{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-tomcat",
    "version": "4.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "11.0.22"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-tomcat-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-tomcat-4.0.8-SNAPSHOT.jar",
          "size": 123503,
          "sha512": "8d13b4b1cec9a3db775a5f29ed4ea3d80f668ca6c34243b092709c5fdb3b8c8f26c11d5370b632b470313cdbebd25bc8209307b701f52615be4812bb52e0bfc1",
          "sha256": "528f1a3aaa2b4fb61b07aefb8ab5f3af97d13de15b9fd3613718a6a53c0c0f32",
          "sha1": "9067b336d9f494e6a0847e1026dcec0aa11210bb",
          "md5": "ca2c742e9c75a9f239d43d8458610a84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "11.0.22"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-tomcat-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-tomcat-4.0.8-SNAPSHOT.jar",
          "size": 123503,
          "sha512": "8d13b4b1cec9a3db775a5f29ed4ea3d80f668ca6c34243b092709c5fdb3b8c8f26c11d5370b632b470313cdbebd25bc8209307b701f52615be4812bb52e0bfc1",
          "sha256": "528f1a3aaa2b4fb61b07aefb8ab5f3af97d13de15b9fd3613718a6a53c0c0f32",
          "sha1": "9067b336d9f494e6a0847e1026dcec0aa11210bb",
          "md5": "ca2c742e9c75a9f239d43d8458610a84"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-tomcat-4.0.8-SNAPSHOT-javadoc.jar",
          "url": "spring-boot-tomcat-4.0.8-SNAPSHOT-javadoc.jar",
          "size": 273526,
          "sha512": "3abb76229e76568e2a09d9bb5010b6b2a7a3eb577de0631a8b78da53d1b5aa81303b7251ef95f53afac50a2cbb037fdca122a3f61b286a35c230b34858227274",
          "sha256": "534ace0100e156ec15ca3a76cb73ae489bbeb1e002a5a4b9349e55256baa9885",
          "sha1": "bb067651364ab56a3b8533986100ba5a6ce68ecf",
          "md5": "1a77e2dae4b23975fd63a926f6352db1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-tomcat-4.0.8-SNAPSHOT-sources.jar",
          "url": "spring-boot-tomcat-4.0.8-SNAPSHOT-sources.jar",
          "size": 78983,
          "sha512": "7753eab66250896fb015fdc5d7033e046d233700e20dec390354aa9a02e040fb00fd66f0f417463333ceb813634e4c5791fc788f16e9d3627a733be25404eeda",
          "sha256": "623b8327d612949ba9df00fc95c02d760496894a738d7f24eef95eac51bc43b7",
          "sha1": "71613708e0021c80631598031193c5480e48781a",
          "md5": "0c15ccf990559f235f7377fbe5859aea"
        }
      ]
    }
  ]
}
