{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-jackson",
    "version": "4.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-jackson-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-jackson-4.0.8-SNAPSHOT.jar",
          "size": 68097,
          "sha512": "1f9318a7ca2a5ac6e484e57f6bd90b0e09b7981d46f4f53b09b193d1c871283bd2f5f200f458fb9a74f22bdee6afe53d65eb9a07a934f9da4a3899a9c600e5b9",
          "sha256": "25675c9fb437889916ab0cf7dabb0f5f02a45a9c54dd9ed2ba2090a00ae7ddb5",
          "sha1": "b830f9737a70f077510394cae6c33def477b5344",
          "md5": "11cd5b0f3241f8b3dde95db0d3d1bc2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-jackson-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-jackson-4.0.8-SNAPSHOT.jar",
          "size": 68097,
          "sha512": "1f9318a7ca2a5ac6e484e57f6bd90b0e09b7981d46f4f53b09b193d1c871283bd2f5f200f458fb9a74f22bdee6afe53d65eb9a07a934f9da4a3899a9c600e5b9",
          "sha256": "25675c9fb437889916ab0cf7dabb0f5f02a45a9c54dd9ed2ba2090a00ae7ddb5",
          "sha1": "b830f9737a70f077510394cae6c33def477b5344",
          "md5": "11cd5b0f3241f8b3dde95db0d3d1bc2d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-jackson-4.0.8-SNAPSHOT-javadoc.jar",
          "url": "spring-boot-jackson-4.0.8-SNAPSHOT-javadoc.jar",
          "size": 177981,
          "sha512": "c009a0177e180ebdfc15a41663ff881ad07ad585f56e90fc74a8d8dcbc6465739b35d427d4ce3d1ba7e7f029ea8a51673b05e74bd4af2bb0f01401f0c922aa18",
          "sha256": "5b28e0def747ff76304c02a8e37f1b0a33014ec15050f7303888702246501f53",
          "sha1": "b0862726101e98a44d9cb0d298fc525465607644",
          "md5": "8a29f5e5bde3a7e03c2b3fc6575202c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-jackson-4.0.8-SNAPSHOT-sources.jar",
          "url": "spring-boot-jackson-4.0.8-SNAPSHOT-sources.jar",
          "size": 35443,
          "sha512": "ebaa724b4c7be11881084c48ff123393b74dc80697aa2010515ab7f24c81afb2d6a4ebebe9699cf898f51185f008d0fbc779d8bd4e3fc95b42540e3e93b063e6",
          "sha256": "0a98404346a186c6e14dec282c50058e392363273fde9f09de1c69a666099ece",
          "sha1": "2fce77036205887ee652d7caa1b64b5181dbddf9",
          "md5": "3f970ef5840967d88e050d868facbb1a"
        }
      ]
    }
  ]
}
