{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-websocket",
    "version": "4.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webmvc",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-websocket",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-websocket-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-starter-websocket-4.0.8-SNAPSHOT.jar",
          "size": 4777,
          "sha512": "d65fa93e7c99f4548394327a6419cac2227e31bd1cba8b278e48cf64224980065588c47c8aaa1ed5bf631b0a3995b46f02bd1f5de942eb04d16b3755fa9be46b",
          "sha256": "1deeffdad5dc1304b4960e9ccd5b2f24c79e1a6b0e36306ed6cc0f0e3dd858e4",
          "sha1": "a8c6a7b193050f37ea92b2bc00c14bf7c5021c89",
          "md5": "05914d3f7e752c9e39538189c2ab2955"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webmvc",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-websocket",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-websocket-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-starter-websocket-4.0.8-SNAPSHOT.jar",
          "size": 4777,
          "sha512": "d65fa93e7c99f4548394327a6419cac2227e31bd1cba8b278e48cf64224980065588c47c8aaa1ed5bf631b0a3995b46f02bd1f5de942eb04d16b3755fa9be46b",
          "sha256": "1deeffdad5dc1304b4960e9ccd5b2f24c79e1a6b0e36306ed6cc0f0e3dd858e4",
          "sha1": "a8c6a7b193050f37ea92b2bc00c14bf7c5021c89",
          "md5": "05914d3f7e752c9e39538189c2ab2955"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-websocket-4.0.8-SNAPSHOT-javadoc.jar",
          "url": "spring-boot-starter-websocket-4.0.8-SNAPSHOT-javadoc.jar",
          "size": 4777,
          "sha512": "d65fa93e7c99f4548394327a6419cac2227e31bd1cba8b278e48cf64224980065588c47c8aaa1ed5bf631b0a3995b46f02bd1f5de942eb04d16b3755fa9be46b",
          "sha256": "1deeffdad5dc1304b4960e9ccd5b2f24c79e1a6b0e36306ed6cc0f0e3dd858e4",
          "sha1": "a8c6a7b193050f37ea92b2bc00c14bf7c5021c89",
          "md5": "05914d3f7e752c9e39538189c2ab2955"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-websocket-4.0.8-SNAPSHOT-sources.jar",
          "url": "spring-boot-starter-websocket-4.0.8-SNAPSHOT-sources.jar",
          "size": 4777,
          "sha512": "d65fa93e7c99f4548394327a6419cac2227e31bd1cba8b278e48cf64224980065588c47c8aaa1ed5bf631b0a3995b46f02bd1f5de942eb04d16b3755fa9be46b",
          "sha256": "1deeffdad5dc1304b4960e9ccd5b2f24c79e1a6b0e36306ed6cc0f0e3dd858e4",
          "sha1": "a8c6a7b193050f37ea92b2bc00c14bf7c5021c89",
          "md5": "05914d3f7e752c9e39538189c2ab2955"
        }
      ]
    }
  ]
}
