{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-thymeleaf",
    "version": "4.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-thymeleaf",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-starter-thymeleaf-4.0.8-SNAPSHOT.jar",
          "size": 4760,
          "sha512": "5943024db69c2be04f2572151137c01c935deb38797bf9d97ee295b8a81b68f32ef5a91052a5adab0b7f91f05c01e388d7181919b196073a749d2ec0369300a7",
          "sha256": "005a4596e2cd46bb6d359411d69682fb9fd7536b5d3a57104bc4a2b3dab53e30",
          "sha1": "2e30435e289db2e356977f6b1e68fca2fc4c8ad2",
          "md5": "a30f662afc4cb2a8e4cbedfd985ed23f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-thymeleaf",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-starter-thymeleaf-4.0.8-SNAPSHOT.jar",
          "size": 4760,
          "sha512": "5943024db69c2be04f2572151137c01c935deb38797bf9d97ee295b8a81b68f32ef5a91052a5adab0b7f91f05c01e388d7181919b196073a749d2ec0369300a7",
          "sha256": "005a4596e2cd46bb6d359411d69682fb9fd7536b5d3a57104bc4a2b3dab53e30",
          "sha1": "2e30435e289db2e356977f6b1e68fca2fc4c8ad2",
          "md5": "a30f662afc4cb2a8e4cbedfd985ed23f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-4.0.8-SNAPSHOT-javadoc.jar",
          "url": "spring-boot-starter-thymeleaf-4.0.8-SNAPSHOT-javadoc.jar",
          "size": 4760,
          "sha512": "5943024db69c2be04f2572151137c01c935deb38797bf9d97ee295b8a81b68f32ef5a91052a5adab0b7f91f05c01e388d7181919b196073a749d2ec0369300a7",
          "sha256": "005a4596e2cd46bb6d359411d69682fb9fd7536b5d3a57104bc4a2b3dab53e30",
          "sha1": "2e30435e289db2e356977f6b1e68fca2fc4c8ad2",
          "md5": "a30f662afc4cb2a8e4cbedfd985ed23f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-4.0.8-SNAPSHOT-sources.jar",
          "url": "spring-boot-starter-thymeleaf-4.0.8-SNAPSHOT-sources.jar",
          "size": 4760,
          "sha512": "5943024db69c2be04f2572151137c01c935deb38797bf9d97ee295b8a81b68f32ef5a91052a5adab0b7f91f05c01e388d7181919b196073a749d2ec0369300a7",
          "sha256": "005a4596e2cd46bb6d359411d69682fb9fd7536b5d3a57104bc4a2b3dab53e30",
          "sha1": "2e30435e289db2e356977f6b1e68fca2fc4c8ad2",
          "md5": "a30f662afc4cb2a8e4cbedfd985ed23f"
        }
      ]
    }
  ]
}
