{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "4.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat-runtime",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-starter-tomcat-4.0.8-SNAPSHOT.jar",
          "size": 4783,
          "sha512": "6413f958289fff266ecad5270a926ecd1d0452bd7986e4e5224a86f0ef334950b741a8d9b291a0cf09bc690c5739a19b7216a2498caa944f6b0b25eccfa95562",
          "sha256": "151087f492a6c038deb3c919b483478cd645fa6cdd9173a264486928307f2ee9",
          "sha1": "0ee0bb2a4c35efb0e5f9da433d779ace9aefc500",
          "md5": "de754fbb1fe3d55d0568320fdb39fa10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat-runtime",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.0.8-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-4.0.8-SNAPSHOT.jar",
          "url": "spring-boot-starter-tomcat-4.0.8-SNAPSHOT.jar",
          "size": 4783,
          "sha512": "6413f958289fff266ecad5270a926ecd1d0452bd7986e4e5224a86f0ef334950b741a8d9b291a0cf09bc690c5739a19b7216a2498caa944f6b0b25eccfa95562",
          "sha256": "151087f492a6c038deb3c919b483478cd645fa6cdd9173a264486928307f2ee9",
          "sha1": "0ee0bb2a4c35efb0e5f9da433d779ace9aefc500",
          "md5": "de754fbb1fe3d55d0568320fdb39fa10"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-4.0.8-SNAPSHOT-javadoc.jar",
          "url": "spring-boot-starter-tomcat-4.0.8-SNAPSHOT-javadoc.jar",
          "size": 4783,
          "sha512": "6413f958289fff266ecad5270a926ecd1d0452bd7986e4e5224a86f0ef334950b741a8d9b291a0cf09bc690c5739a19b7216a2498caa944f6b0b25eccfa95562",
          "sha256": "151087f492a6c038deb3c919b483478cd645fa6cdd9173a264486928307f2ee9",
          "sha1": "0ee0bb2a4c35efb0e5f9da433d779ace9aefc500",
          "md5": "de754fbb1fe3d55d0568320fdb39fa10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-4.0.8-SNAPSHOT-sources.jar",
          "url": "spring-boot-starter-tomcat-4.0.8-SNAPSHOT-sources.jar",
          "size": 4783,
          "sha512": "6413f958289fff266ecad5270a926ecd1d0452bd7986e4e5224a86f0ef334950b741a8d9b291a0cf09bc690c5739a19b7216a2498caa944f6b0b25eccfa95562",
          "sha256": "151087f492a6c038deb3c919b483478cd645fa6cdd9173a264486928307f2ee9",
          "sha1": "0ee0bb2a4c35efb0e5f9da433d779ace9aefc500",
          "md5": "de754fbb1fe3d55d0568320fdb39fa10"
        }
      ]
    }
  ]
}
